### ISSUE TITLE
stackprof fails to build native extensions on ubuntu 22.04 and ruby 3.2.2

### ISSUE THREAD

**Issue by jeffsaremi** [tmm1/stackprof#216]
Tried 0.2.25 and a few earlier versions. All produce this results.
```
#11 35.83 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#11 35.83
#11 35.83 current directory:
#11 35.83 /usr/local/bundle/ruby/3.2.0/gems/stackprof-0.2.25/ext/stackprof
#11 35.83 /usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/3.2.0 -r
#11 35.83 ./siteconf20230726-20-45uwmc.rb extconf.rb
#11 35.83 checking for rb_postponed_job_register_one()... no
#11 35.83 *** extconf.rb failed ***
#11 35.83 Could not create Makefile due to some reason, probably lack of necessary
#11 35.83 libraries and/or headers.  Check the mkmf.log file for more details.  You may
#11 35.83 need configuration options.
#11 35.83
#11 35.83 Provided configuration options:
#11 35.83 	--with-opt-dir
#11 35.83 	--without-opt-dir
#11 35.83 	--with-opt-include
#11 35.83 	--without-opt-include=${opt-dir}/include
#11 35.83 	--with-opt-lib
#11 35.83 	--without-opt-lib=${opt-dir}/lib
#11 35.83 	--with-make-prog
#11 35.83 	--without-make-prog
#11 35.83 	--srcdir=.
#11 35.83 	--curdir
#11 35.83 	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
#11 35.83 extconf.rb:14:in `<main>': missing API: are you using ruby 2.1+? (RuntimeError)
#11 35.83
#11 35.83 To see why this extension failed to compile, please check the mkmf.log which can
#11 35.83 be found here:
#11 35.83
#11 35.83 /usr/local/bundle/ruby/3.2.0/extensions/x86_64-linux/3.2.0-static/stackprof-0.2.25/mkmf.log
#11 35.83
#11 35.83 extconf failed, exit code 1
#11 35.83
#11 35.83 Gem files will remain installed in
#11 35.83 /usr/local/bundle/ruby/3.2.0/gems/stackprof-0.2.25 for inspection.
#11 35.83 Results logged to
#11 35.83 /usr/local/bundle/ruby/3.2.0/extensions/x86_64-linux/3.2.0-static/stackprof-0.2.25/gem_make.out
#11 35.83
#11 35.83   /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:95:in `run'
#11 35.83 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:47:in
#11 35.83 `block in build'
#11 35.83   /usr/local/lib/ruby/3.2.0/tempfile.rb:331:in `open'
#11 35.83 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:26:in
#11 35.83 `build'
#11 35.83 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:161:in
#11 35.83 `build_extension'
#11 35.83 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:195:in `block in
#11 35.83 build_extensions'
#11 35.83   /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:192:in `each'
#11 35.83 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:192:in
#11 35.83 `build_extensions'
#11 35.83 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:847:in
#11 35.83 `build_extensions'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/rubygems_gem_installer.rb:72:in
#11 35.83 `build_extensions'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/rubygems_gem_installer.rb:28:in
#11 35.83 `install'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/source/rubygems.rb:200:in
#11 35.83 `install'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/installer/gem_installer.rb:54:in
#11 35.83 `install'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/installer/gem_installer.rb:16:in
#11 35.83 `install_from_spec'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:156:in
#11 35.83 `do_install'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:147:in
#11 35.83 `block in worker_pool'
#11 35.83   /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/worker.rb:62:in `apply_func'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/worker.rb:57:in `block in
#11 35.83 process_queue'
#11 35.83   /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/worker.rb:54:in `loop'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/worker.rb:54:in
#11 35.83 `process_queue'
#11 35.83 /usr/local/bundle/gems/bundler-2.4.8/lib/bundler/worker.rb:90:in `block (2
#11 35.83 levels) in create_threads'
#11 35.83
#11 35.83 An error occurred while installing stackprof (0.2.25), and Bundler cannot
#11 35.83 continue.
#11 35.83
#11 35.83 In Gemfile:
#11 35.83   stackprof
                libbz2-dev \
                libc6-dev \
                libcurl4-openssl-dev \
                libdb-dev \
                libevent-dev \
                libglib2.0-dev \
                libjpeg-dev \
                libtool \
                git \
                echo 'install: --no-document'; \
```

**Comment by jeffsaremi** [comment]
cannot reproduce myself
